/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MapRouteImport } from './routes/map'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as CodesRouteImport } from './routes/codes'
import { Route as BooksRouteImport } from './routes/books'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionIdRouteImport } from './routes/section.$id'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const CodesRoute = CodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionIdRoute = SectionIdRouteImport.update({
  id: '/section/$id',
  path: '/section/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/codes': typeof CodesRoute
  '/images': typeof ImagesRoute
  '/map': typeof MapRoute
  '/settings': typeof SettingsRoute
  '/todos': typeof TodosRoute
  '/section/$id': typeof SectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/codes': typeof CodesRoute
  '/images': typeof ImagesRoute
  '/map': typeof MapRoute
  '/settings': typeof SettingsRoute
  '/todos': typeof TodosRoute
  '/section/$id': typeof SectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/codes': typeof CodesRoute
  '/images': typeof ImagesRoute
  '/map': typeof MapRoute
  '/settings': typeof SettingsRoute
  '/todos': typeof TodosRoute
  '/section/$id': typeof SectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/codes'
    | '/images'
    | '/map'
    | '/settings'
    | '/todos'
    | '/section/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/books'
    | '/codes'
    | '/images'
    | '/map'
    | '/settings'
    | '/todos'
    | '/section/$id'
  id:
    | '__root__'
    | '/'
    | '/books'
    | '/codes'
    | '/images'
    | '/map'
    | '/settings'
    | '/todos'
    | '/section/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksRoute: typeof BooksRoute
  CodesRoute: typeof CodesRoute
  ImagesRoute: typeof ImagesRoute
  MapRoute: typeof MapRoute
  SettingsRoute: typeof SettingsRoute
  TodosRoute: typeof TodosRoute
  SectionIdRoute: typeof SectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codes': {
      id: '/codes'
      path: '/codes'
      fullPath: '/codes'
      preLoaderRoute: typeof CodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section/$id': {
      id: '/section/$id'
      path: '/section/$id'
      fullPath: '/section/$id'
      preLoaderRoute: typeof SectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRoute: BooksRoute,
  CodesRoute: CodesRoute,
  ImagesRoute: ImagesRoute,
  MapRoute: MapRoute,
  SettingsRoute: SettingsRoute,
  TodosRoute: TodosRoute,
  SectionIdRoute: SectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
